# Generated by Django 5.2.14 on 2026-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0182_remove_org_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role_code',
            field=models.CharField(choices=[('A', 'Administrator'), ('E', 'Editor'), ('V', 'Viewer'), ('T', 'Agent')], default='E', max_length=1),
        ),
    ]
