# Generated by Django 5.2.14 on 2026-06-25 23:39

import storages.backends.s3
import temba.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_last_auth_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(bucket_name='rapidpro-attachments', querystring_auth=False, signature_version='s3v4'), upload_to=temba.utils.fields.UploadToIdPathAndRename('avatars/')),
        ),
    ]
